spring:
  datasource:
#    url: jdbc:postgresql://10.140.0.2:5432/postgresql
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
  rabbitmq:
    host: 10.178.0.27
    username: guest
    password: guest
    prot: 5672